// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAo1n1uHSw4S3j8VuPBEQtt66pZxWNr0',
    appId: '1:969984256199:web:8a6ff6257e778c259076e2',
    messagingSenderId: '969984256199',
    projectId: 'profile-app-e549d',
    authDomain: 'profile-app-e549d.firebaseapp.com',
    storageBucket: 'profile-app-e549d.firebasestorage.app',
    measurementId: 'G-8KD62K8G9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZ13A0riyPQuinbWmcaWCObV80zO5cMg',
    appId: '1:969984256199:android:358cbc6922392f0e9076e2',
    messagingSenderId: '969984256199',
    projectId: 'profile-app-e549d',
    storageBucket: 'profile-app-e549d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANbrvlFSAbQdM4J7YbWO3If4e2m7J2PLw',
    appId: '1:969984256199:ios:06a006d27b58d1fc9076e2',
    messagingSenderId: '969984256199',
    projectId: 'profile-app-e549d',
    storageBucket: 'profile-app-e549d.firebasestorage.app',
    iosBundleId: 'com.example.profileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANbrvlFSAbQdM4J7YbWO3If4e2m7J2PLw',
    appId: '1:969984256199:ios:06a006d27b58d1fc9076e2',
    messagingSenderId: '969984256199',
    projectId: 'profile-app-e549d',
    storageBucket: 'profile-app-e549d.firebasestorage.app',
    iosBundleId: 'com.example.profileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeAo1n1uHSw4S3j8VuPBEQtt66pZxWNr0',
    appId: '1:969984256199:web:0631b5073144cc309076e2',
    messagingSenderId: '969984256199',
    projectId: 'profile-app-e549d',
    authDomain: 'profile-app-e549d.firebaseapp.com',
    storageBucket: 'profile-app-e549d.firebasestorage.app',
    measurementId: 'G-VFSB4WGCXE',
  );
}
